# set base image (host OS)
FROM nikolaik/python-nodejs:latest

# set the working directory in the container
# WORKDIR /code

# copy the dependencies file to the working directory
COPY requirements.txt .

# install dependencies
RUN pip install -r requirements.txt
RUN npm install -g nodemon

COPY . .

# command to run on container start
CMD [ "python", "./SHModelUtils.py" ]